### ISSUE TITLE
Differentiate instructions link to make it clear it's a modal

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-playground#2]
<img width="520" alt="screenshot of safari 26-07-17 2-28-43 pm" src="https://user-images.githubusercontent.com/811954/28601854-cbc8cabe-720e-11e7-9cf0-c06e3218aa90.png">

All four links show up the same here. It would be good for the instructions link to look different to indicate it's not going to redirect the user and lose their work. I'm not exactly sure what would work here, maybe a disclosure triangle, or maybe something else?

**Comment by saskali** [comment]
We decided to replace the instruction link with an svg info icon to make it more clear that current progress won't be lost. Pushed the changes just now!

**Comment by danielcompton** [comment]
Looks good!
